apiVersion: {{ template "daemonset_api_version" . }}
kind: DaemonSet
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ template "fluentd.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
{{- if .Values.updateStrategy }}
  updateStrategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "fluentd.name" . }}
      chart: {{ template "fluentd.version" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fluentd.name" . }}
        chart: {{ template "fluentd.version" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    {{- if .Values.labels }}
    {{ toYaml .Values.labels | indent 4 }}
    {{- end }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "fluentd.fullname" . }}
      containers:
      - name: {{ template "fluentd.fullname" . }}
        image:  {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- if .Values.command }}
        command: {{ .Values.command }}
        {{ end }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: custom
          mountPath: {{ .Values.container.custom }}
        - name: config
          mountPath: {{ .Values.container.config }}
        - name: entry
          mountPath: {{ .Values.container.entry }}
        - name: ssl
          mountPath: {{ .Values.container.ssl }}
        - name: dockerroot
          mountPath: {{ .Values.container.dockerRoot }}
        - name: varlogcontainers
          mountPath: {{ .Values.container.varlogcontainers }}
        - name: varlogpods
          mountPath: {{ .Values.container.varlogpods }}
        - name: rkelog
          mountPath: {{ .Values.container.rkelog }}
        - name: customlog
          mountPath: {{ .Values.container.customlog }}
        - name: fluentdlog
          mountPath: {{ .Values.container.fluentdlog }}
        - name: libsystemddir
          mountPath: {{ .Values.container.libsystemddir }}
          readOnly: true
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
        ports:
{{- range $port := .Values.service.ports }}
          - name: {{ $port.name }}
            containerPort: {{ $port.port }}
{{- if $port.protocol }}
            protocol: {{ $port.protocol }}
{{- end }}
{{- end }}
{{- if .Values.livenessProbe.enabled }}
        # Liveness probe is aimed to help in situarions where fluentd
        # silently hangs for no apparent reasons until manual restart.
        # The idea of this probe is that if fluentd is not queueing or
        # flushing chunks for 5 minutes, something is not right. If
        # you want to change the fluentd configuration, reducing amount of
        # logs fluentd collects, consider changing the threshold or turning
        # liveness probe off completely.
        livenessProbe:
          initialDelaySeconds: 600
          periodSeconds: 60
          exec:
            command:
            - '/bin/sh'
            - '-c'
            - >
              LIVENESS_THRESHOLD_SECONDS=${LIVENESS_THRESHOLD_SECONDS:-300};
              STUCK_THRESHOLD_SECONDS=${LIVENESS_THRESHOLD_SECONDS:-900};
              if [ ! -e {{ .Values.container.fluentdlog }}/buffer ];
              then
                exit 1;
              fi;
              touch -d "${STUCK_THRESHOLD_SECONDS} seconds ago" /tmp/marker-stuck;
              if [[ -z "$(find {{ .Values.container.fluentdlog }}/buffer -type f -newer /tmp/marker-stuck -print -quit)" ]];
              then
                rm -rf {{ .Values.container.fluentdlog }}/buffer;
                exit 1;
              fi;
              touch -d "${LIVENESS_THRESHOLD_SECONDS} seconds ago" /tmp/marker-liveness;
              if [[ -z "$(find {{ .Values.container.fluentdlog }}/buffer -type f -newer /tmp/marker-liveness -print -quit)" ]];
              then
                exit 1;
              fi;
{{- end }}
      - name: {{ template "fluentd.fullname" . }}-{{ .Values.configmapReload.name }}
        image: {{ template "system_default_registry" . }}{{ .Values.configmapReload.image.repository }}:{{ .Values.configmapReload.image.tag }}
        imagePullPolicy: "{{ .Values.configmapReload.image.pullPolicy }}"
        args:
          - --volume-dir={{ .Values.container.custom }}
          - --volume-dir={{ .Values.container.config }}
          - --volume-dir={{ .Values.container.ssl }}
          - --volume-dir={{ .Values.container.entry }}
          - --webhook-method=GET
          - --webhook-url=http://127.0.0.1:24444/api/config.reload
        resources:
        {{ toYaml .Values.configmapReload.resources | indent 12 }}
        volumeMounts:
          - name: custom
            mountPath: {{ .Values.container.custom }}
          - name: config
            mountPath: {{ .Values.container.config }}
          - name: entry
            mountPath: {{ .Values.container.entry }}
          - name: ssl
            mountPath: {{ .Values.container.ssl }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: custom
        hostPath:
          path: {{ .Values.cluster.custom }}
      - name: dockerroot
        hostPath:
          path: {{ .Values.cluster.dockerRoot }}
      - name: varlogcontainers
        hostPath:
          path: {{ .Values.cluster.varlogcontainers }}
      - name: varlogpods
        hostPath:
          path: {{ .Values.cluster.varlogpods }}
      - name: rkelog
        hostPath:
          path: {{ .Values.cluster.rkelog }}
      - name: customlog
        hostPath:
          path: {{ .Values.cluster.customlog }}
      - name: fluentdlog
        hostPath:
          path: {{ .Values.cluster.fluentdlog }}
      - name: config
        secret:
          secretName: {{ template "fluentd.fullname" . }}
      - name: entry
        secret:
          secretName: {{ template "fluentd.fullname" . }}-entry
      - name: ssl
        secret:
          secretName: {{ template "fluentd.fullname" . }}-ssl
      - name: libsystemddir
        hostPath:
          path: {{ .Values.cluster.libsystemddir }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
