apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-{{ .Release.Name }}
  labels:
    app: {{ template "app.fullname" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: ui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.fullname" . }}
      chart: {{ .Chart.Name }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
      component: ui
  template:
    metadata:
      labels:
        app: {{ template "app.fullname" . }}
        chart: {{ .Chart.Name }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        component: ui
    spec:
      containers:
        - name: ui
          image: "{{ template "system_default_registry" . }}{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
          - name: API_TOKEN
            value: "{{ .Values.apiToken }}"
          - name: SERVER_URL
            {{- if .Values.grpcProxyUrl }}
            value: "http://rancher.cattle-system"
            {{- else }}
            value: "https://{{ .Values.rancherHost }}"
            {{- end }}
          - name: THANOS_URL
            value: "http://access-thanos"
  {{- if .Values.ui.title }}
          - name: CUSTOM_RANCHER_TITLE
            value: {{ .Values.ui.title }}
  {{- end }}
  {{- if .Values.ui.tabTitle }}
          - name: CUSTOM_RANCHER_TAB_TITLE
            value: {{ .Values.ui.tabTitle }}
  {{- end }}
  {{- if .Values.ui.favicon }}
          - name: CUSTOM_RANCHER_FAVICON
            value: {{ .Values.ui.favicon }}
  {{- end }}
  {{- if .Values.ui.logo }}
          - name: CUSTOM_RANCHER_LOGO
            value: {{ .Values.ui.logo }}
  {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      nodeSelector:
      {{- include "linux-node-selector" . | nindent 8 }}
      {{- with .Values.ui.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- include "linux-node-tolerations" . | nindent 8 }}
      {{- with .Values.ui.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
